### ISSUE TITLE
New currency implementation is broken

### ISSUE THREAD

**Issue by andrewkett** [Laybuy/magento2#10]
# Preconditions
- Laybuy_LaybuyPayments 1.0.3
- Magento 2.2.4
- PHP 7.1.10
- Nginx

# Steps to reproduce
- Install Laybuy_LaybuyPayments on clean Magento install and configure with API key.
- Checkout as guest using Laybuy payment method and place order

# Expected result
User is forwarded to Laybuy to complete checkout

# Actual result
rest/default/V1/guest-carts/{id}/payment-information returns a 500 error meaning that the user is never directed to laybuy and checkout cannot be completed.

# Detail

On guest checkout rest/default/V1/guest-carts/{id}/payment-information is returning the following response:

`{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/1420785284611"}]}}`

The error report shows

`Uncaught Error: Call to undefined method Laybuy\\LaybuyPayments\\Gateway\\Config\\Config::getCurrency() in \/var\/www\/src\/app\/code\/Laybuy\/LaybuyPayments\/Gateway\/Request\/CaptureRequest.php:71
`

It looks like \Laybuy\LaybuyPayments\Gateway\Config doesn't have a getCurrency method implemented, I am guessing this code got missed from the commit maybe?

The same error happens for logged in customers through rest/default/V1/carts/mine/payment-information

**Comment by 16hands** [comment]
Hi Andrew, my apologies; your quite right, this is about to be committed correctly

**Comment by andrewkett** [comment]
Hey @16hands, this works but I was still getting errors until I manually created a config in the db for payment_currency, and then subsequently found the new admin config. https://github.com/Laybuy/magento2/pull/11 addresses this by defaulting to NZD if a currency is not explicitly set in core_config_data
