### ISSUE TITLE
No default currency config provided by extension, this can break payment method if no database config is set

### ISSUE THREAD

**Issue by andrewkett** [Laybuy/magento2#12]
# Preconditions
- Laybuy_LaybuyPayments 1.1.0
- Magento 2.2.4
- PHP 7.1.10
- Nginx

# Steps to reproduce
- Install Laybuy_LaybuyPayments on clean Magento install and configure with API key.
- Checkout using Laybuy payment method and place order

# Expected result
User is redirected to Laybuy to complete checkout

# Actual result 

No redirect happens, we see the following errors in our logs:

```
==> log/magento/payment.log <==
[2018-06-20 11:27:05] main.DEBUG: array (
  'redirect response body' =>
  stdClass::__set_state(array(
     'result' => 'ERROR',
     'error' => 'Specified currency is invalid.',
  )),
) [] []
[2018-06-20 11:27:05] main.DEBUG: array (
  'FAILED TO GET returnURL' =>
  stdClass::__set_state(array(
     'result' => 'ERROR',
     'error' => 'Specified currency is invalid.',
  )),
) [] []
```

see https://github.com/Laybuy/Magento-2/pull/11

**Comment by 16hands** [comment]
Hi Andrew 

sorry for missing this, we hav enow added a default to the module's config.xml
