### ISSUE TITLE
Thank You for your Order email not sent out on checkout.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/magento2#16]
Just making an issue to track something a customer complained about with this payment method.
Note: I have not attempt to reproduce it yet.

The standard Magento Order Completion email "Thank You for your Order email etc" is not sent out.
```This customer has a survey link in the email that they want customers to have access to.```

I'll investigate a fix for this further when I get a chance, other payment methods do send this email out.

Suspect need to set up an event + observer.

```xml
    <event name="checkout_onepage_controller_success_action">
        <observer name="checkout_onepage_controller_success_action_sendmail" instance="Laybuy\LaybuyPayments\Observer\SendMailOnOrderSuccess" />
    </event>
```

Link that may be of help: https://magento.stackexchange.com/questions/154595/magento-2-order-confirmation-email-sending-before-payment-gatway-redirection

**Comment by nikolai-overdose** [comment]
Hi @LiamKarlMitchell - just confirming we can now close this issue?

Cheers

**Comment by LiamKarlMitchell** [comment]
Has it been fixed?

**Comment by LiamKarlMitchell** [comment]
Yes this has been resolved thank you.
