### ISSUE TITLE
Stock is decremented twice

### ISSUE THREAD

**Issue by andrewkett** [Laybuy/magento2#2]
# Preconditions
- Laybuy_LaybuyPayments 1.0.1
- Magento 2.2.4
- PHP 7.1.10
- Nginx

# Steps to reproduce
- Install Laybuy_LaybuyPayments on clean Magento 2.2.4 and configure with API key.
- Set stock level to 1 on a given product
- Checkout that product as customer (guest doesn't work due to https://github.com/Laybuy/magento2/issues/1 ) using Laybuy payment method and click place order 
- Complete Laybuy payment and return to Magento

# Expected result
Order created, order confirmation shown

# Actual result
Customer returned to cart and "Laybuy payment was Cancelled", "Not all of your products are available in the requested quantity." messages are shown.

This seems to be because when the transaction is started the stock level of the product being checked out is decremented. When the user is returned to Magento the stock is then decremented again when the order is created.

Similarly if there are initially 2 products in stock the customer can checkout but the stock level goes from 2 to 0 even though only 1 item has been purchased.

**Comment by 16hands** [comment]
Hi Andrew, thanks for the wonderfully clear issue report
what are your settings in the Laybuy Gateway admin screen? could you post a screenshot (without the laybuy keys readable )

**Comment by andrewkett** [comment]
![screen shot 2018-06-12 at 12 31 35 pm](https://user-images.githubusercontent.com/2080313/41263676-a2ab4816-6e3c-11e8-9a46-baf25e069659.png)

**Comment by 16hands** [comment]
Thanks Andrew, we will have a look over this in the next few days and get back to you (and the Guest issue)

**Comment by andrewkett** [comment]
Hey @16hands. Thanks for this, your update does indeed stop completed orders from decrementing stock twice. This will certainly help with the stock issues we were having. 

Unfortunately we're still seeing a few remaining issues:

- If only 1 product is in stock customers still get "Not all of your products are available in the requested quantity" when they return from Laybuy, the Laybuy order is subsequently cancelled. 
- If a customer drops out during the Laybuy process without returning to Magento the stock is still decremented. If we had a number of people do this it could deplete stock without any orders actually being placed.
