### ISSUE TITLE
Option to show Logo's of Laybuy on checkout payment method selection?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/magento2#3]
Is it possible to add logo images of Laybuy to the payment method?

Example: 
![image](https://user-images.githubusercontent.com/1968109/41325234-625f3e6c-6f0d-11e8-90ef-96dba817f1c5.png)

**Comment by LiamKarlMitchell** [comment]
Added this in here is what the result looks like.
![image](https://user-images.githubusercontent.com/1968109/41384345-4e04ba70-6fc9-11e8-8ce9-45a9df26eb34.png)

**Comment by 16hands** [comment]
Hi Liam

Thanks again, I have pull these in with the 0f50065 commit
