### ISSUE TITLE
API Key and Merchant ID are publicly exposed.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Laybuy/magento2#6]
Hi, I don't know if this is a security concern or not but I noticed the api_key and merchant_id are exposed to the front facing end.

Check the javascript object
```js
window.checkoutConfig.payment.laybuy_laybuypayments
```

Could someone do bad with this info?
From what I can tell the other module's don't make it public.

Removing the keys from ConfigProvider.php's getConfig method does not appear to break the integration those values do not appear to be used client side.
```
                self::CODE => [
                    //'isActive' => $this->config->isActive(),
                    //'merchant_id' => $this->config->getMerchantId(),
                    //'api_key' => $this->config->getApiKey(),
                    //'sandbox_merchant_id' => $this->config->getSandboxMerchantId(),
                    //'sandbox_api_key'     => $this->config->getSandboxApiKey(),
                    //'use_sandbox' => $this->config->getUseSandbox(),
                    'payment_method_image' => $this->config->getPaymentMethodImage(),
                ],
```

**Comment by 16hands** [comment]
HI Liam 

Thanks for identifying this, we used stripe as a guide for Magento 2 and of course they need theses exposed, we will update to suit.
